name: pokedex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.6
  injectable: ^2.3.2

  auto_route: ^7.8.4

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  intl: ^0.19.0
  stream_transform: ^2.1.0
  flutter_web_frame: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.4.0
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/files/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

flutter_gen:
  output: lib/presentation/
  line_length: 100